### ISSUE TITLE
Logged-in users should not access log in screen

### ISSUE THREAD

**Issue by pexea12** [anhtumai/roomie-frontend#1]
Logged-in users can still access log in screen from https://roomiee.netlify.app/

![image](https://user-images.githubusercontent.com/10600525/142779328-a29523c1-8e82-499a-a4e6-b08e821f3061.png)

Suggested bug fix: https://roomiee.netlify.app/ should redirect the user to https://roomiee.netlify.app/home when the user is authenticated.

**Comment by anhtumai** [comment]
Reason: / is auto redirected to /login.
